案件3　修正
Ryuzo-Nakamura/ShoppingSite pull request #9
Opened 2023-08-03 07:24 UTC by Ryuzo-Nakamura

@git-fuji-hub 
feature/3ブランチにて案件3に関するファイル追加及び修正を行いました。

＜追加＞
・Word.java　→　検索ワード情報のデータをまとめるBeanクラス
　・検索ワード情報のカラムとなるメンバ変数の定義及びそれらのgetter,setterの定義
・WordDAO.java　→　検索ワード情報テーブル(word_info)にアクセスするDAO
　・search01メソッド定義（引数のWORDとWORD_TYPEをもつレコードの数を取得）
　・search02メソッド定義（引数のWORD_TYPEをもつレコードの数を取得）
　・insert01メソッド定義（引数のWordクラスオブジェクトをテーブルに追加）
・WordAdd.java　→　検索ワード情報を検索ワードテーブルに追加するサーブレット​
　・リクエスト属性の出版社、作者、ジャンルを検索ワード情報としてテーブルに追加する処理

＜修正＞
・MangaSearch.java
　・検索ワードをキーに検索ワード情報を検索し、ワードタイプによって出版社(1)、作者(2)、出版社(3)、タイトルマンガ(なし)としてマンガ情報を検索するか場合分けをするよう修正　[51-59,81-89行]
・MangaAdd.java
　・マンガ情報追加成功時、リクエスト属性に出版社、作者、ジャンルの値を格納し、WordAdd.javaにディスパッチする処理を追加　[51-54行]
・MangaUpdate.java
　・マンガ情報更新成功時、リクエスト属性に出版社、作者、ジャンルの値を格納し、WordAdd.javaにディスパッチする処理を追加　[39-42行]

ご確認のほどよろしくお願いいたします。

2023-08-03 15:47 UTC, git-fuji-hub requested changes

2023-08-03 15:47 UTC, git-fuji-hub commented on src/main/java/jp/co/aforce/servlet/MangaSearch.java
> +					}
コメントアウトがあると見やすくなると思います。
一般的には処理の上の行にコメントアウトを記載していきます。

実際には実装した本人以外もソースを読み、解析・修正するので、
できるだけ見やすくなるように心掛けるとよいと思います。

コメントアウトが多すぎるのも逆に見づらくなったり、
どれが正解というものはないので、一度練習してみましょう。

全クラスに反映するのは多すぎるので、練習で`MangaSearch.java`だけコメントアウト記載してみてください。

(例)
```
// ○○の場合
if(wordDAO.search01(w, 1) >= 1) {
	list.addAll(mangaDAO.search05(w));
// ××の場合
}else if(wordDAO.search01(w, 2) >= 1) {
	list.addAll(mangaDAO.search06(w));
// ▼▼の場合
}else if(wordDAO.search01(w, 3) >= 1) {
	list.addAll(mangaDAO.search07(w));
// それ以外
}else {
	list.addAll(mangaDAO.search04(w));
}

// ★★の件数分繰り返し
for(int i = 0 ; i < list.size(); i++) {

}

// ◇◇を設定
session.setAttribute("mangaList", mangaList);

if(sort == 2) {
　　// @@のため、？？リストを反転
	Collections.reverse(mangaList);
}
```

2023-08-03 15:56 UTC, git-fuji-hub requested changes

2023-08-03 15:56 UTC, git-fuji-hub commented on src/main/java/jp/co/aforce/dao/WordDAO.java
> +	public int search01(String word, int type) throws Exception {
`WordDAO.java`も各メソッドにコメントをつけてみましょう。
メソッド名を選択した状態で`Alt + Shift + j`でコメントをメソッド上部に出すことができます。
パラメータや戻り値がどういうものなのか記載すると、このメソッドがどういう処理をしているのか分かりやすくなります。
実際には各開発現場でこのように書きましょうというのが`コーディング規約`というもので定められています。

例
```
	/**
	 * ○○と△△を条件に★★を検索するメソッド。
	 * @param word ○○
	 * @param type △△
	 * @return 検索結果の件数
	 * @throws Exception
	 */
	public int search01(String word, int type) throws Exception {
```

2023-08-04 02:29 UTC, Ryuzo-Nakamura commented
@git-fuji-hub 
コメント対応を行いましたので、新たにpushいたしました。
変更点はMangaDAO.java,MangaSearch.javaどちらもコメントアウト追加のみです。

ご確認のほどよろしくお願いします。

2023-08-04 02:52 UTC, merged